/*----------------D1_1 Hands-on----------------
1) Role-based access control (RBAC)
2) Discretionary access control (DAC)
3) Roles & Privileges
4) Privilege Inheritance
----------------------------------------------*/
 
-- Set context 
USE ROLE ACCOUNTADMIN;

SHOW ROLES;
SELECT "name", "comment" FROM TABLE(result_scan(last_query_id()));

SHOW GRANTS TO ROLE SECURITYADMIN;

-- Create Database and Schema
USE ROLE SYSADMIN;

CREATE DATABASE FILMS_DB;
CREATE SCHEMA FILMS_SCHEMA;

CREATE TABLE FILMS_SYSADMIN
(
  ID STRING, 
  TITLE STRING,  
  RELEASE_DATE DATE,
  RATING INT
);


-- Create custom role inherited by SYSADMIN system-defined role
USE ROLE SECURITYADMIN;

CREATE ROLE ANALYST;

GRANT USAGE
  ON DATABASE FILMS_DB
  TO ROLE ANALYST;

GRANT USAGE, CREATE TABLE
  ON SCHEMA FILMS_DB.FILMS_SCHEMA
  TO ROLE ANALYST;

GRANT USAGE
  ON WAREHOUSE COMPUTE_WH
  TO ROLE ANALYST;
  
GRANT ROLE ANALYST TO ROLE SYSADMIN;

GRANT ROLE ANALYST TO USER ADMIN;

-- Verify privileges 
SHOW GRANTS TO ROLE SYSADMIN;

SHOW GRANTS OF ROLE ANALYST;

SHOW GRANTS TO ROLE ANALYST;

-- Set context
USE ROLE ANALYST;
USE SCHEMA FILMS_DB.FILMS_SCHEMA;

CREATE TABLE FILMS_ANALYST
(
  ID STRING, 
  TITLE STRING,  
  RELEASE_DATE DATE,
  RATING INT
);

SHOW TABLES;

SHOW DATABASES;
SELECT "name", "owner" FROM TABLE(result_scan(last_query_id()));

-- GRANT OWNERSHIP ON DATABASE FILMS_DB TO ROLE ANALYST;

USE ROLE SYSADMIN;
SHOW TABLES;

-- Future grants
USE ROLE SECURITYADMIN;

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FILMS_DB TO ROLE ANALYST;

USE ROLE SYSADMIN;

CREATE SCHEMA MUSIC_SCHEMA;

CREATE SCHEMA BOOKS_SCHEMA;

SHOW SCHEMAS;

USE ROLE ANALYST;
SHOW SCHEMAS;

SHOW GRANTS TO ROLE ANALYST;


--Create user
USE ROLE USERADMIN;

CREATE USER Rajesh PASSWORD='temp' DEFAULT_ROLE = analyst DEFAULT_WAREHOUSE='COMPUTE_WH' MUST_CHANGE_PASSWORD=TRUE;

USE ROLE SECURITYADMIN;

GRANT ROLE analyst TO USER Rajesh;


USE SCHEMA FILMS_DB.FILMS_SCHEMA;

SHOW TABLES;

-- Clear-down resources
USE ROLE SYSADMIN;
DROP DATABASE FILMS_DB;
